### ISSUE TITLE
Joining forces ...

### ISSUE THREAD

**Issue by swade1987** [naquada/deprek8#12]
Is it worth us joining forces and maintaining a single repo moving forward (see https://github.com/swade1987/deprek8ion)?

**Comment by RomeroDiver** [comment]
Please do it - really would like to use the `swade1987/deprek8ion` with github actions

**Comment by swade1987** [comment]
@RomeroDiver I think @tylerauerbeck has/is working on it.

**Comment by nicolasbernard** [comment]
Hi,

I was on a break since few months but I will resume deprek8 maintenance asap.

I have some ideas that I have already started working on, I'm going to finish them to show which direction I want to go.

I'm happy to discuss how we can work together.

**Comment by swade1987** [comment]
hope you had a good break @nicolasbernard

**Comment by nlamirault** [comment]
There is also this repository : https://github.com/instrumenta/policies
