### ISSUE TITLE
the rego filename should reflect the k8s version it is written for

### ISSUE THREAD

**Issue by cruschke** [naquada/deprek8#9]
The current `deprek8.rego` is written for `1.16`, when a new Kubernetes version is released with breaking API changes my `conftest` run would apparently require a different policy file.

That's why I propose the rego filename should reflect the Kubernetes version it is written for.

So instead of running `conftest test -p deprek8.rego ...` one would run `conftest test -p deprek8_1_16.rego ...` 

Seems more future proof to me.

**Comment by nicolasbernard** [comment]
As today it's the point.

Projects should (and don't always do) announce deprecations months in advance, the mission of deprek8 is to be always cutting edge to warn you "this think will break soon, you should upgrade now, the new API already works".

**Comment by cruschke** [comment]
If I would `git clone` this rego in my deployment pipeline, my pipeline might break at any time because of a new release of a rego file (because of a new Kubernetes version). If you add individual regos for individual Kubernetes versions then it is my decision when my pipeline break.

Furthermore managed Kubernetes offerings usually have a significant delay in supporting the most recent versions of Kubernetes (e.g. vanilla Kubernetes is 1.16, current AWS EKS is 1.14), so probably I would want my deployment pipeline (or Helm chart release process) explicitely to tell what to verify for. 

Maybe providing a `latest` rego policy if I want cutting edge?

**Comment by nicolasbernard** [comment]
I understand what you say but it's out of scope for now.

Conftest git support is on the way (https://github.com/instrumenta/conftest/pull/107), I guess you can pin an old commit in your CI.

If you don't (or can't) have a recent Kubernetes cluster version, there is less value to use deprek8, nothing should break if you don't upgrade.

Deprek8 can probably be useful in a non-blocking CI job, just to list work before next upgrades.
